module.exports = {
    ROOM_ENTERED: 'ROOM_ENTERED',
    FORBID_ROOM: 'FORBID_ROOM',
    UPDATE_BOARD_SER:'UPDATE_BOARD_SER',
    WILL_BUILD_BOARD:'WILL_BUILD_BOARD',
    SEND_BOARD_SNAKE_TO_CLIENT:'SEND_BOARD_SNAKE_TO_CLIENT',
    UPDATE_SCORES:'UPDATE_SCORES',
    SEND_GAME_OVER:'SEND_GAME_OVER'
}