export const ROOM_ENTERED = 'ROOM_ENTERED';
export const FORBID_ROOM = 'FORBID_ROOM';
export const SEND_BOARD_SNAKE_TO_CLIENT = 'SEND_BOARD_SNAKE_TO_CLIENT';
export const UPDATE_SCORES = 'UPDATE_SCORES';
